fix PotcarSingleTest.test_multi_potcar_with_and_without_hash()
seems like missing file error was due to a typo in filename introduced in #2776

FileNotFoundError: [Errno 2] No such file or directory: 'test_files/POT_GGA_PAW_PBE_54/POTCAR.Fe_O.gz'