Breaking: Have plot methods return `plt.Axes` object, not `matplotlib` module (#3237)
* return plt.Axes instead of plt from plot methods

* VoltageProfilePlotter.get_plot and get_chgint_plot

* fix >           plt.subplot(220 + count)
E           AttributeError: 'Axes' object has no attribute 'subplot'

/home/runner/work/pymatgen/pymatgen/pymatgen/electronic_structure/plotter.py:1082

* fix >           ylim = plt.ylim()
E           AttributeError: 'Axes' object has no attribute 'ylim'

/home/runner/work/pymatgen/pymatgen/pymatgen/electronic_structure/plotter.py:3834

* fix >       plt.gca().set_xticks(uniq_d)
E       AttributeError: 'Axes' object has no attribute 'gca'

/home/runner/work/pymatgen/pymatgen/pymatgen/electronic_structure/plotter.py:360:

* fix >           ylim = plt.ylim()
E           AttributeError: 'Axes' object has no attribute 'ylim'

/home/runner/work/pymatgen/pymatgen/pymatgen/electronic_structure/plotter.py:3838: AttributeError

* fix mypy and add type hints to RelaxationAnalyzer

* fix >           ax.xlim((min(relevanty), max(relevanty)))
E           AttributeError: 'Axes' object has no attribute 'xlim'

pymatgen/electronic_structure/plotter.py:3836: AttributeError

* fix >       plt.gca().set_xticks(uniq_d)
E       AttributeError: 'Axes' object has no attribute 'gca'

/home/runner/work/pymatgen/pymatgen/pymatgen/phonon/plotter.py:266: AttributeError

* don't use get_plot return value, use imported plt module directly

* improve plot_compare_gs error message on incompatible plotters

* update SpectrumPlotter.get_plot and pretty_polyfit_plot

* fix >       ax.setp(legend_text, fontsize=30)
E       AttributeError: 'Axes' object has no attribute 'setp'

pymatgen/electronic_structure/plotter.py:3875: AttributeError

* return plt.axes instead of plt in SurfaceEnergyPlotter.surface_chempot_range_map and get_ir_spectra

* fix PhononDosPlotter.get_plot()

* refactor tests

* update test_gruneisen.py and electronic_structure/test_plotter.py to expect plt.axes instead of plt

* fix SpectrumPlotter.get_plot and DosPlotter.get_plot

* remove redundant os.path.join(".", ...) in pymatgen/io/feff/sets.py

* replace all plt = pretty_plot(...) with ax = pretty_plot(...) and fix downstream repercussions

* add missing set_ prefix to Axes methods

* fix AttributeError: 'Axes' object has no attribute 'gca'

    def test_plot(self):
        # Disabling latex for testing.
        from matplotlib import axes, rc

        rc("text", usetex=False)
        self.plotter.add_dos("Total", self.dos)
        self.plotter.get_plot(units="mev")
        self.plotter_nostack.add_dos("Total", self.dos)
        plt = self.plotter_nostack.get_plot(units="mev")

>       ax = plt.gca()

also attempt fix get_elt_projected_plots

* update return type doc strings and type hints

* pre-commit autoupdate && ruff . --fix

* rename all subplot vars to ax

* fix AttributeError: 'Axes' object has no attribute 'ylim'

>       assert plt.ylim() == (-4.0, 7.6348), "wrong ylim"

and

>       ax.set_title(ax.get_title(), size=width * 4)
E       AttributeError: 'numpy.ndarray' object has no attribute 'set_title'

* fix TestBSPlotter.test_get_plot()