Fix `ruff` PLC0206 and PLR6104 (#4035)
* fix ruff PLC0206

* fix/ignore ruff PLR6104

* simplify np.prod(arr.shape) -> arr.size

* add missing args to get_partial_doses doc str

* fix ruff N818 Exception name `SymmetryUndetermined` should be named with an Error suffix

* fix TestGruneisenParameter.test_average_gruneisen

    def test_average_gruneisen(self):
        assert self.gruneisen_obj.average_gruneisen() == approx(1.164231026696211)
>       assert self.gruneisen_obj.average_gruneisen(squared=False) == approx(0.849759667411049)
E       assert 1.3554338835221134 == 0.849759667411049 ± 8.5e-07
E
E         comparison failed
E         Obtained: 1.3554338835221134
E         Expected: 0.849759667411049 ± 8.5e-07

* auto-format .github/workflows/issue-metrics.yml

* rename index variables